name: NodeJS TS Frontend Application Deployment via Nginx

on:
  push:
    branches: [main]  # Change to your branch
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    environment: production # 🔐 Enables environment-specific secrets

    steps:
      - name: Clone the project
        uses: actions/checkout@v3
      
      - name: 📦 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/ds.pem
          chmod 600 ~/.ssh/ds.pem
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
            
      - name: Building Frontend
        run: |
          cd ./frontend
          echo "${{ vars.FE_ENV_NON_SEN_DATA }}" > .env
          echo "${{ secrets.FE_ENV_SEN_DATA }}" >> .env
          npm i
          npm run build
          rm -rf .env
      
      - name: Frontend Deployment
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/ds.pem" ./frontend/dist/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USER }}/frontend/
          ssh -i ~/.ssh/ds.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} <<EOF
            sudo rm -rf /var/www/html/*
            sudo cp -r /home/${{ secrets.SERVER_USER }}/frontend/* /var/www/html/
            sudo systemctl restart nginx
          EOF
      
      - name: Cleanup SSH key
        run: rm -f ~/.ssh/ds.pem

